
export default [
  {
    id: 1,
    postedOn: "2023-10-23",
    title: "Frontend Developer",
    company: "Google",
    type: "Full-time",
    experience: "Mid-level",
    location: "Remote",
    skills: ["JavaScript", "CSS", "Git"],
    job_link: "https://careers.google.com/jobs/frontend-developer",
  },
  {
    id: 2,
    postedOn: "2023-10-20",
    title: "Backend Developer",
    company: "Amazon",
    type: "Full-time",
    experience: "Senior-level",
    location: "On-site",
    skills: ["Node.js", "Express", "AWS"],
    job_link: "https://amazon.jobs/backend-developer",
  },
  {
    id: 3,
    postedOn: "2023-10-18",
    title: "Full-Stack Developer",
    company: "Microsoft",
    type: "Contract",
    experience: "Mid-level",
    location: "Hybrid",
    skills: ["React.js", "Node.js", "SQL"],
    job_link: "https://careers.microsoft.com/jobs/fullstack-developer",
  },
  {
    id: 4,
    postedOn: "2023-10-25",
    title: "UI/UX Designer",
    company: "Meta",
    type: "Part-time",
    experience: "Entry-level",
    location: "Remote",
    skills: ["Figma", "Adobe XD", "CSS"],
    job_link: "https://meta.careers/uiux-designer",
  },
  {
    id: 5,
    postedOn: "2023-10-22",
    title: "DevOps Engineer",
    company: "Netflix",
    type: "Full-time",
    experience: "Mid-level",
    location: "On-site",
    skills: ["Docker", "Kubernetes", "CI/CD"],
    job_link: "https://jobs.netflix.com/devops-engineer",
  },
];
